package com.andrewsozonov.urbanride.util

object Constants {

    const val LOCATION_PERMISSION_REQUEST_CODE = 1
    const val START_LOCATION_SERVICE = "START_LOCATION_SERVICE"
    const val PAUSE_LOCATION_SERVICE = "PAUSE_LOCATION_SERVICE"
    const val STOP_LOCATION_SERVICE = "STOP_LOCATION_SERVICE"
    const val NOTIFICATION_CHANNEL_ID = "LOCATION_CHANNEL"
    const val NOTIFICATION_CHANNEL_NAME = "LOCATION"
    const val NOTIFICATION_ID = 1
    const val ACTION_SHOW_RIDING_FRAGMENT = "ACTION_SHOW_RIDING_FRAGMENT"

    const val SERVICE_STATUS_STARTED = "Started"
    const val SERVICE_STATUS_STOPPED = "Stopped"
    const val SERVICE_STATUS_PAUSED = "Paused"

    const val POLYLINE_WIDTH = 12f
    const val GRAPH_PADDING = 20

    const val LOCATION_UPDATE_INTERVAL = 5000L
    const val TIMER_DELAY = 1000L
    const val RECYCLER_ITEMS_SPACING = 20

    const val BUNDLE_RIDE_ID_KEY = "id_key"

    const val SHARE_IMAGE_TEXT_SIZE = 48f
    const val SHARE_IMAGE_STROKE_WIDTH = 0.5f
    const val SHARE_IMAGE_TEXT_HORIZONTAL_MARGIN = 40f
    const val SHARE_IMAGE_TEXT_VERTICAL_MARGIN = 30f


}