package com.andrewsozonov.urbanride.util

object Constants {

    const val LOCATION_PERMISSION_REQUEST_CODE = 1
    const val START_LOCATION_SERVICE = "START_LOCATION_SERVICE"
    const val PAUSE_LOCATION_SERVICE = "PAUSE_LOCATION_SERVICE"
    const val STOP_LOCATION_SERVICE = "STOP_LOCATION_SERVICE"
    const val NOTIFICATION_CHANNEL_ID = "LOCATION_CHANNEl"
    const val NOTIFICATION_CHANNEL_NAME = "LOCATION"
    const val NOTIFICATION_ID = 1
    const val ACTION_SHOW_RIDING_FRAGMENT = "ACTION_SHOW_RIDING_FRAGMENT"


}